### ISSUE TITLE
RSE Alloc Chart misaligned?

### ISSUE THREAD

**Issue by grenville** [RSE-Sheffield/RSEAdmin#177] opened 2022-01-17 16:27 UTC
Hi, the RSE Allocations chart doesn't quite agree with the dates for RSE workers - please see the attached. What is the significance of the thin blue line (through March?)

G
![alloc](https://user-images.githubusercontent.com/3245953/149806441-8900b23f-d0b3-4987-b191-2ee29312124e.png)

**Comment by mondus** [comment] 2022-01-17 19:29
This is a duplicate of #146 which I suspect is a bug in the JS gantt library. The thin blue line is the current date (which in your example is also offset incorrectly).

**Closed by mondus** 2022-01-17 19:29 UTC
Labels: duplicate
